### ISSUE TITLE
执行命令或许输出问题

### ISSUE THREAD

**Issue by saowu** [NoCortY/WebSSH#26]
发送什么，就接收什么，没有其他内容呀
![image](https://user-images.githubusercontent.com/33569619/223670724-b87b83dc-1f77-4572-8005-d24544f86b1e.png)

**Comment by eric20141111** [comment]
你好，这个问题后来解决了么？我也遇到了

**Comment by saowu** [comment]
解决了，没有加换行符`\r`

**Comment by saowu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            解决了，没有加换行符\r
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                吴延博
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年03月16日 11:45
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [NoCortY/WebSSH] 执行命令或许输出问题 (Issue #26)
        
      
    
  
  
你好，这个问题后来解决了么？我也遇到了

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by eric20141111** [comment]
> 

感谢
